spring:

  kafka:
    bootstrap-servers: localhost:9092

  profiles:
    active: prod

  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/appdatabase?authSource=admin

  jpa:
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5432/booking_system
    username: postgres
    password: postgres
    hikari:
      schema: booking_schema
      connection-timeout: 10000
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS booking_schema


app:
  uploading:
    mockHotelPath: src/main/resources/data/data.json

  dateFormat: "dd/MM/yyyy"

  kafka:
    kafkaGroupId: "kafka-booking-group-id"
    userTopic: "user-service-topic"
    reservationTopic: "reservation-service-topic"